version: "3.3"
services:
  redis:
    image: redis:alpine
    volumes:
      - ./redis/redis.conf:/path/to/redis.conf
    command:
      - "redis-server"
    ports:
      - "6379:6379"
    restart: always
  proxy: #nginx
    image: nginx:alpine
    container_name: web-proxy
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      #- "27017:27017" linked to mongodb?
    depends_on:
      - node-app
  node-app:
    restart: always
    depends_on:
      - redis
    build: .
    #ports:
    #  - "5000:80" #localhost => localhost:5000
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    links:
      - redis
